version: '3.2'

services:

  wordpress:
    image: wordpress:5.9.0-fpm-alpine
    container_name: blog-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    # Mount to a host folder in order to leverage existing data backup mechanism of the underlying data disk.
    volumes:
      - ${WORDPRESS_LOCAL_DIR}:/var/www/html

  apache:
    build: './apache/'
    container_name: blog-apache
    depends_on:
      - wordpress
    restart: always
    ports:
      - ${APACHE_PORT}:80
    # Mount to the same host folder so that static requests will be handled by apache itself. 
    volumes:
      - ${WORDPRESS_LOCAL_DIR}:/var/www/html
    links:
      - wordpress

  db:
    image: mysql:8.0
    container_name: blog-db
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DB_LOCAL_DIR}:/var/lib/mysql
