version: '3.7'

services:

  wordpress:
    hostname: wordpress
    image: wordpress:5.9.0-fpm-alpine
    container_name: blog-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WP_MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${WP_MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_MYSQL_DATABASE}
    networks:
      - common_backend
    # Mount to a host folder in order to leverage existing data backup mechanism of the underlying data disk.
    volumes:
      - ${WP_WEB_LOCAL_DIR}:${WP_WEB_INST_DIR}

  # This apache server run as a reverse proxy that forward requests onto backend services, including the wordpress. 
  apache:
    hostname: apache
    build: './apache/'
    container_name: blog-apache
    depends_on:
      - wordpress
    restart: always
    ports:
      - ${WP_APACHE_PORT}:80
    environment:
      WORDPRESS_HOST_NAME: ${WP_HOST_NAME}
      WORDPRESS_INST_DIR: ${WP_WEB_INST_DIR}
      WIKI_HOST_NAME: ${WIKI_HOST_NAME}
      WIKI_PROXY_TARGET: ${WIKI_PROXY_TARGET}
    networks:
      - common_backend
      - frontend
    # Mount to the same host folder so that static requests will be handled by apache itself. 
    volumes:
      - ${WP_WEB_LOCAL_DIR}:${WP_WEB_INST_DIR}

  db:
    hostname: db
    image: mysql:8.0
    container_name: blog-db
    restart: always
    ports:
      - ${WP_MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${WP_MYSQL_DATABASE}
      MYSQL_USER: ${WP_MYSQL_USER}
      MYSQL_PASSWORD: ${WP_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WP_MYSQL_ROOT_PASSWORD}
    networks:
      - common_backend
    volumes:
      - ${WP_DB_LOCAL_DIR}:/var/lib/mysql

networks:
  common_backend:
    # This network is intended to be shared among all compose.
    # Set a explicit name to get rid of the automatic prefix.
    name: common_backend
  frontend:
