version: '3.2'

services:

  wordpress:
    image: wordpress:5.9.0-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - site:/var/www/html

  apache:
    build: './apache/'
    depends_on:
      - wordpress
      - db
    restart: always
    ports:
      - 8088:80
    volumes:
      - site:/var/www/html
    links:
      - wordpress
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db:/var/lib/mysql

volumes:
  site:
  db:
