version: '3.2'

services:

  wordpress:
    image: wordpress:5.9.0-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: wordpress
    # Mount to a host folder in order to leverage existing data backup mechanism of the underlying data disk.
    volumes:
      - ./html:/var/www/html

  apache:
    build: './apache/'
    depends_on:
      - wordpress
      - db
    restart: always
    ports:
      - 8088:80
    # Mount to the same host folder so that static requests will be handled by apache itself. 
    volumes:
      - ./html:/var/www/html
    links:
      - wordpress
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
